### ISSUE TITLE
Icon rotating on the custom:button-card

### ISSUE THREAD

**Issue by Krzysztonek** [3ative/Icon-Speeds#1]
Dear @3ative David, 

Again, thank you so much for your kind response from yesterday evening, got on your YT channel. After a full night, spent on coding this custom button-card and using `@keyframes` section I'm still not able to get the desired result. From the formal point of view, the code has been (at least it looks like) completed, but it doesn't work as designed. Sorry for stealing your spare time again but it would be great if you'd take a look at [my button-card code](https://github.com/Krzysztonek/custom-button-card/blob/main/HA%20button-card%20code) and point out what am I doing wrong... 

The scenario for this button-card should be as follows:

When the valve is open, its icon `mdi:valve-open` should display opened position, with gold color. When it is closed (triggered by clicking the icon), the same icon should be slowly (10 sec) rotated 90 deg left, then it should change its color from gold to dark grey, and then remain steady with its new rotated position at the end of the animation until next click, which will open the valve back. Please, kindly advise how to get the following visual effect:
1. Toggling the valve on the HA dashboard (from CLOSE towards OPEN position) should trigger a rotation of the icon from CLOSE (dark grey 90 deg) to OPEN (gold 0 deg) position, and then the icon should stay in this position until next closing click is triggered.
2. Toggling the valve on the HA dashboard (from OPEN towards CLOSE position) should trigger a reversed rotation of the icon from OPEN (gold 0 deg) to CLOSE (dark grey 90 deg) position, and then the icon should stay in this position until next opening click is triggered.

![image](https://user-images.githubusercontent.com/87784133/152650779-ea584544-64d2-47fa-9d00-d4a9dca6e58d.png)

Would you be so kind as to indicate what is wrong with my code, please? It still doesn't work as expected. I'm stuck..

**Comment by 3ative** [comment]
I see what you're trying to do now. I've download your code example, and I'll see what I can do for you asap.

**Comment by Krzysztonek** [comment]
David, I'm aware of stealing your spare time..., so, please take your time! This is definitely not what is worth spending a weekend time on. :)
Nevertheless, I'd encourage you to make an additional video someday to show the tricks-and-tips for this button-card...

**Comment by 3ative** [comment]
@Krzysztonek 
Thanks but, I do enjoy a challenge 😊
The trouble is... While the browser will allow two "keyframe" setups, I.E. one 'forward' and one 'backward' animation. Custom Button Card strictly states this is not implemented or allowed. With any additional 'keyframe' code ignored - in favour of the first.😢

Therefore, a work-around is needed. Of course this would be easy with a couple of animated GIFs - But, we don't want that! LOL
My quest to find a procedural solution will continue 👌

**Comment by 3ative** [comment]
@Krzysztonek Belay my last....

**I DID IT!!!**  🥳🥳🥳🥳🥳

_Lemme rewrite and test your code and I'll post it here soon._

**Comment by 3ative** [comment]
@Krzysztonek 

I changed the Entity ID (Line 3) for one of my own for testing. Also, you'll need to change the timings on the animations - _again I used a different number for testing._

## Here you go:
```yaml
type: custom:button-card
name: Gas Valve
entity: input_boolean.tut_button 
icon: mdi:valve-open
color_type: state
tap_action:
  action: toggle
extra_styles: |
  @keyframes move_valve_right {100%{transform:rotatez(90deg)}}
  @keyframes move_valve_left  {100%{transform:rotatez(90deg)}}
styles:
  card:
    - font-size: 14px
    - width: min(20vw, 150px)
    - height: min(20vw, 150px)
    - margin: 8px
    - border-radius: 15px
    - border-style: solid
    - font-size: 14px
    - border-width: 5px
    - border-color: aqua
    - background-color: var(--primary-background-color)
state:
  - value: 'on'
    styles:
      icon:
        - animation: move_valve_right 1s ease both
        - color: gold
    label: open
  - value: 'off'
    styles:
      icon:
        - animation: move_valve_left 1s ease reverse both
        - color: darkgrey
    label: close
show_name: true
show_label: true
```

I hope I've earned a YouTube Sub and maybe a Coffee ? 😉
